# Generated by Django 5.1.1 on 2024-09-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0002_rename_name_product_nama_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nama',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='harga',
            new_name='price',
        ),
    ]
