# Generated by Django 5.1.1 on 2024-09-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0005_product_user_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
