# Generated by Django 5.1.1 on 2024-09-18 04:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
